"""project version table

Revision ID: d74fb2915aeb
Revises: 0006
Create Date: 2026-05-03 14:18:45.077730
"""
from alembic import op
import sqlalchemy as sa


revision = '0007'
down_revision = '0006'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('parent_version_id', sa.Integer(), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('schema_snapshot', sa.JSON(), nullable=False),
    sa.Column('global_notes_snapshot', sa.Text(), nullable=False),
    sa.Column('model_id_snapshot', sa.String(length=128), nullable=False),
    sa.Column('counterexample_ids', sa.JSON(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('source_metadata', sa.JSON(), nullable=False),
    sa.Column('locked', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("source IN ('initial','user_edit','auto_research')", name='ck_project_version_source'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_version_id'], ['project_versions.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'version_number', name='uq_project_version_number')
    )
    op.create_index(op.f('ix_project_versions_project_id'), 'project_versions', ['project_id'], unique=False)
    # ### end Alembic commands ###

    # Tighten projects.active_version_id: add FK to project_versions.id
    with op.batch_alter_table('projects') as batch_op:
        batch_op.create_foreign_key(
            'fk_projects_active_version_id',
            'project_versions',
            ['active_version_id'],
            ['id'],
        )


def downgrade() -> None:
    # Remove FK from projects.active_version_id before dropping project_versions
    with op.batch_alter_table('projects') as batch_op:
        batch_op.drop_constraint('fk_projects_active_version_id', type_='foreignkey')

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_versions_project_id'), table_name='project_versions')
    op.drop_table('project_versions')
    # ### end Alembic commands ###
